const { encode, decode } = require('./Utils/encoding.js')
const fs = require('fs')
const  { File, TRAINER_INFO }  = require('./Classes/File.js')
test = new File('Pokemon - Emerald Version (USA, Europe).sav')
console.log(test.TRAINER_INFO._playerGender)